// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type TodoInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	UserID      int64   `json:"user_id"`
}

type UserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
