// Code generated by sqlc. DO NOT EDIT.
// source: todos.sql

package pg

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, description)
VALUES ($1, $2)
RETURNING id, title, description, user_id
`

type CreateTodoParams struct {
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Title, arg.Description)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :one
DELETE FROM todos
WHERE id = $1
RETURNING id, title, description, user_id
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, deleteTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, description, user_id from todos
WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, user_id FROM todos
ORDER BY title
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUserID = `-- name: ListTodosByUserID :many
SELECT todos.id, todos.title, todos.description, todos.user_id FROM todos, users
WHERE users.id = todos.user_id AND todos.user_id = $1
`

func (q *Queries) ListTodosByUserID(ctx context.Context, userID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2, description = $3
WHERE id = $1
RETURNING id, title, description, user_id
`

type UpdateTodoParams struct {
	ID          int64
	Title       string
	Description sql.NullString
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo, arg.ID, arg.Title, arg.Description)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
	)
	return i, err
}
